# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
use_bioc: true
bioc_required: true
cache: packages
sudo: false
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
env:
  global:
  - R_REMOTES_NO_ERRORS_FROM_WARNINGS=true
  # don't treat missing suggested packages as error
  - _R_CHECK_FORCE_SUGGESTS_=false
  # remove linux
  - TRAVIS_CXXFLAGS="-Wall -Wextra -pedantic -Werror"
