# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @author Schuyler D. Smith
aligned_BLAST_sequences <- function(FASTQ_file_path, aligned_reads, output_path, aligned = FALSE) {
    .Call('_ssBLAST_aligned_BLAST_sequences', PACKAGE = 'ssBLAST', FASTQ_file_path, aligned_reads, output_path, aligned)
}

